from gpt3_assistant.exceptions.listener_error import ListenerError


class FailedToUnderstandListenerError(ListenerError):
    pass
