from gpt3_assistant.exceptions.listener_error import ListenerError


class ListenerFatalError(ListenerError):
    pass
